import { join } from 'node:path';
import { loadConfig } from '../lib/generators/config.js';
import { loadStorybook } from '../lib/navigation/load-storybook.js';
import { validate, type Diagnostic } from '../lib/navigation/validate.js';
import { flatten } from '../lib/navigation/flatten.js';
import { renderNative } from '../lib/navigation/render-native.js';
import { renderWeb } from '../lib/navigation/render-web.js';
import { renderRoutesDts, type RouteParam } from '../lib/navigation/render-routes-dts.js';
import { safeWrite } from '../lib/generators/write.js';
import { log } from '../util/log.js';

export interface BuildNavOptions {
  cwd: string;
  watch?: boolean;
  force?: boolean;
}

/** Import specifier the generated navigation pulls screen components from. */
const SCREENS_IMPORT = './screens';

const BARREL = [
  '// AUTO-GENERATED by sublime build:nav — do not edit',
  "export { Navigation } from './navigation.js';",
  "export type { AppRoutes } from './routes.js';",
  '',
].join('\n');

function printDiagnostics(platform: string, diagnostics: Diagnostic[]): void {
  for (const d of diagnostics) {
    log.error(`[${platform}] ${d.rule}: ${d.message}`);
  }
}

/**
 * Compile the per-platform storybooks into navigation artifacts.
 *
 * Loads `storybook.native.ts` (mobile) and `storybook.web.ts` (web) from the
 * project's `navigationDir`, validates each against its platform's rules, and —
 * only when both are clean — renders and force-writes the four generated files
 * (`navigation.native.tsx`, `navigation.web.tsx`, `routes.d.ts`, `index.ts`).
 * On any validation error it prints diagnostics and writes nothing.
 *
 * @returns process exit code (0 success, 1 on validation/load failure).
 */
export async function buildNav(opts: BuildNavOptions): Promise<number> {
  const cfg = loadConfig(opts.cwd);
  const navDir = join(opts.cwd, cfg.navigationDir);
  const nativeFile = join(navDir, 'storybook.native.ts');
  const webFile = join(navDir, 'storybook.web.ts');

  let nativeRoot;
  let webRoot;
  try {
    nativeRoot = await loadStorybook(nativeFile);
    webRoot = await loadStorybook(webFile);
  } catch (err) {
    log.error(err instanceof Error ? err.message : String(err));
    return 1;
  }

  const diagnostics = [
    ...validate(nativeRoot, 'mobile').map((d) => ['native', d] as const),
    ...validate(webRoot, 'web').map((d) => ['web', d] as const),
  ];
  if (diagnostics.length > 0) {
    for (const [platform, d] of diagnostics) printDiagnostics(platform, [d]);
    log.error(`build:nav failed with ${diagnostics.length} error(s); wrote nothing.`);
    return 1;
  }

  const nativeSrc = renderNative(nativeRoot, { screensImport: SCREENS_IMPORT });
  const webSrc = renderWeb(webRoot, { screensImport: SCREENS_IMPORT });

  // Route param types come from the native tree (the canonical route set);
  // params are erased at runtime, so every route defaults to `void`.
  const routeParams: RouteParam[] = flatten(nativeRoot).routes.map((r) => ({
    key: r.key,
    params: 'void',
  }));
  const dtsSrc = renderRoutesDts(routeParams);

  // Generated files are owned by the generator: force-overwrite unconditionally.
  safeWrite(join(navDir, 'navigation.native.tsx'), nativeSrc, true);
  safeWrite(join(navDir, 'navigation.web.tsx'), webSrc, true);
  safeWrite(join(navDir, 'routes.d.ts'), dtsSrc, true);
  safeWrite(join(navDir, 'index.ts'), BARREL, true);

  log.success(`build:nav wrote 4 files to ${navDir}`);
  return 0;
}
