// AUTO-GENERATED by sublime build:nav — do not edit
import type { ComponentType, ReactNode } from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
const Tab = createBottomTabNavigator();
import { createNativeStackNavigator } from '@react-navigation/native-stack';
const Stack = createNativeStackNavigator();
import { NavHeader, NavProvider } from '@sublime-ui/ui/navigation';
import { useNativeNav } from '@sublime-ui/ui/navigation/bridge.native';
import { Home, ProductDetail, Profile } from './screens';

function NavIcon(_props: { name: string }): ReactNode {
  return null;
}

function SettingsNavigator() {
  return (
    <Stack.Navigator screenOptions={{ header: (props) => <NavHeader {...props} /> }}>
      <Stack.Screen name="profile" component={withNav(Profile)} options={{ title: "Profile" }} />
    </Stack.Navigator>
  );
}

function RootNavigator() {
  return (
    <Tab.Navigator screenOptions={{ header: (props) => <NavHeader {...props} /> }}>
      <Tab.Screen name="home" component={withNav(Home)} options={{ title: "Home", tabBarIcon: () => <NavIcon name={"home"} /> }} />
      <Tab.Screen name="product" component={withNav(ProductDetail)} options={{ title: "Product" }} />
      <Tab.Screen name="settings" component={SettingsNavigator} options={{ title: "Settings", tabBarIcon: () => <NavIcon name={"cog"} />, headerShown: false }} />
    </Tab.Navigator>
  );
}

function withNav<P extends object>(Component: ComponentType<P>): ComponentType<P> {
  return function NavBridge(props: P): ReactNode {
    const nav = useNativeNav();
    return (
      <NavProvider value={nav}>
        <Component {...props} />
      </NavProvider>
    );
  };
}

export function Navigation() {
  return (
    <NavigationContainer>
      <RootNavigator />
    </NavigationContainer>
  );
}
