// AUTO-GENERATED by sublime build:nav — do not edit
import type { ReactNode } from 'react';
import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';
import { NavProvider } from '@sublime-ui/ui/navigation';
import { useWebNav } from '@sublime-ui/ui/navigation/bridge.web';
import { Home, ProductDetail, Profile } from './screens';

const paths: Record<string, string> = {
  "home": "/home",
  "product": "/product",
  "profile": "/settings/profile",
};

function pathOf(name: string, params?: unknown): string {
  let path = paths[name] ?? '/';
  if (params && typeof params === 'object') {
    for (const [k, v] of Object.entries(params as Record<string, unknown>)) {
      path = path.replace(`:${k}`, String(v));
    }
  }
  return path;
}

function nameOf(path: string): string {
  for (const [name, p] of Object.entries(paths)) {
    if (p === path) return name;
  }
  return path;
}

function Sidebar() {
  return <Outlet />;
}

function Stack() {
  return <Outlet />;
}

function NavBridge({ children }: { children: ReactNode }) {
  const nav = useWebNav(pathOf, nameOf);
  return <NavProvider value={nav}>{children}</NavProvider>;
}

export function Navigation() {
  return (
    <BrowserRouter>
      <NavBridge>
        <Routes>
      <Route path="/" element={<Sidebar />}>
        <Route path="home" element={<Home />} />
        <Route path="product" element={<ProductDetail />} />
      <Route path="settings" element={<Stack />}>
        <Route path="profile" element={<Profile />} />
      </Route>
      </Route>
        </Routes>
      </NavBridge>
    </BrowserRouter>
  );
}
