// AUTO-GENERATED by sublime build:nav — do not edit
import type { ReactNode } from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
const Tab = createBottomTabNavigator();
import { createNativeStackNavigator } from '@react-navigation/native-stack';
const Stack = createNativeStackNavigator();
import { NavProvider } from '@sublime-ui/ui/navigation';
import { useNativeNav } from '@sublime-ui/ui/navigation/bridge.native';
import { Home, ProductDetail, Profile } from './screens';

function SettingsNavigator() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="profile" component={Profile} />
    </Stack.Navigator>
  );
}

function RootNavigator() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="home" component={Home} />
      <Tab.Screen name="product" component={ProductDetail} />
      <Tab.Screen name="settings" component={SettingsNavigator} />
    </Tab.Navigator>
  );
}

function NavBridge({ children }: { children: ReactNode }) {
  const nav = useNativeNav();
  return <NavProvider value={nav}>{children}</NavProvider>;
}

export function Navigation() {
  return (
    <NavigationContainer>
      <NavBridge>
        <RootNavigator />
      </NavBridge>
    </NavigationContainer>
  );
}
