import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar is auto-generated from the docs/ folder structure.
 * Each subfolder's _category_.json controls its label and position.
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
